volumes:
  redis-data:
    driver: local

services:
  redis:
    image: "redis:${REDIS_VERSION:?error}"
    ports:
      # Default Redis port. Change in .env file as required.
      - "${REDIS_PORT:?error}:6379/tcp"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
